version: '3.3'

services:
  app:
    build: .
    volumes:
      - ./app:/app
    networks:
      - default
    ports:
      - 1643:80
    restart: always
    environment:
      - BASE_URL=192.168.0.101/
      - DB_NAME=codimd
      - USER_NAME=codimd
      - USER_PASSWD=change_password
      - DB_HOST=database
      - DB_PORT=5432
  database:
    image: groonga/pgroonga:2.3.3-alpine-11
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=change_password
      - POSTGRES_DB=codimd
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
    #ports:
    #  - 5433:5432
    networks:
      - default
  codimd:
    # you can use image or custom build below,
    # if you need CJK character with exported PDF files,
    # please change the image tag with `cjk` postfix version
    image: nabo.codimd.dev/hackmdio/hackmd:latest
    # image: nabo.codimd.dev/hackmdio/hackmd:2.1.0-cjk
    # build:
    #   context: ..
    #   dockerfile: ./deployments/Dockerfile
    environment:
      - CMD_DB_URL=postgres://codimd:change_password@database/codimd
      - CMD_USECDN=false
    depends_on:
      - database
    ports:
      - "1234:3000"
    volumes:
      - ./upload:/home/hackmd/app/public/uploads
    restart: always
    networks:
      - default

#networks:
#  proxy:
#    external: true
